// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV4A6Kw0255FEPXWEtwgeOTIMW2ZpC5Do',
    appId: '1:715790868859:web:65fb5fbbab98a3445d5dde',
    messagingSenderId: '715790868859',
    projectId: 'skillcroma-web',
    authDomain: 'skillcroma-web.firebaseapp.com',
    storageBucket: 'skillcroma-web.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCylrj6je3CpBRewzIoYFrKqySS98u-PF4',
    appId: '1:715790868859:android:19cf8f61b751353d5d5dde',
    messagingSenderId: '715790868859',
    projectId: 'skillcroma-web',
    storageBucket: 'skillcroma-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLZ9oWtkIVUL_I79v_HUEdBNaeKjQp-8I',
    appId: '1:715790868859:ios:fac3e8a45c127ee15d5dde',
    messagingSenderId: '715790868859',
    projectId: 'skillcroma-web',
    storageBucket: 'skillcroma-web.firebasestorage.app',
    iosBundleId: 'web.skillcroma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLZ9oWtkIVUL_I79v_HUEdBNaeKjQp-8I',
    appId: '1:715790868859:ios:fac3e8a45c127ee15d5dde',
    messagingSenderId: '715790868859',
    projectId: 'skillcroma-web',
    storageBucket: 'skillcroma-web.firebasestorage.app',
    iosBundleId: 'web.skillcroma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV4A6Kw0255FEPXWEtwgeOTIMW2ZpC5Do',
    appId: '1:715790868859:web:73769c1d4a8237d05d5dde',
    messagingSenderId: '715790868859',
    projectId: 'skillcroma-web',
    authDomain: 'skillcroma-web.firebaseapp.com',
    storageBucket: 'skillcroma-web.firebasestorage.app',
  );
}
